### ISSUE TITLE
Two instances of live wallpaper

### ISSUE THREAD

**Issue by ghost** [GLWallpaperService/GLWallpaperService#11]
Can you help me how to sync the instances to get only one?
I just developing a live wallpaper and there is a lot of memory in this lwp because the two instances. 

Can you help me?

**Comment by markfguerra** [comment]
I'm not really sure what you're asking for. Two instances? Do you mean two projects?

**Comment by blackdigger** [comment]
i guess its about 2 instances of wallpaper engine which exist in the same wallpaper service.
it happens when wallpaper is already set to the home screen and you launch wallpaper preview

**Comment by markfguerra** [comment]
Not sure if this is still an issue, but if so we can maybe re-open this.
